### ISSUE TITLE
How to use it ?

### ISSUE THREAD

**Issue by stephane-lb** [pyp22/NuxSFM-2.0#1]
Hi Pierre Yves,

As I said on youtube this project looks really cool I would love to test it. Unfortunately, this repo do not seem to be link to any site, so I can't add it to my pacman.conf. Could you explain me shortly what I have to do please ? Except if you post them on AUR. 

Have a really good day, 

Stephane

**Comment by pyp22** [comment]
Hi Stephane,
You're right, i have to write some docs ;-) I did not have enough free time since i ported it on Arch. For the moment you have to build packages on your own using the classical way :
Following explainations assume that you're root user (no sudo i hate that. But it works too of course). I understood that your were familiar with building from AUR. 
1/ git clone https://github.com/pyp22/NuxSFM-2.0.git
2/ Build & install from stable and testing dirs all packages :
pacman -Syu base-devel gcc-fortran (to install basics compilation tools)
makepkg -s -i 
-s: will fetch official Arch deps
-i: will install your package
You'll have to compil almost everything from this scripts repo. Except you what you don't need or don't want of course. A good way to start is to begin with openMVG. Try to compil it first. It won't work of course as Arch repo is not providing everything we need. Just follow and compile then what openMVG needs and which scripts are available from this Git.
The short roadmap. To quickly understand why i'm not using AUR and how to go on with thoses actual building scripts:
1/ The distro will come first has a virtual machine (Virtual Box) to be able to test it without replacing or installing a new Linux. That means it will have to be light and will have by default to get rid of devel stuff (headers, compilo and so on). That's the reason why i have to rewrite almost everything to split pakages. For example, openMVG comes in several pakages:
'openMVG' = working binaires & libs
'openMVG-qt' = GCP tool binary running under QT UI
'openMVG-tests' = some demos and tests suite
'openMVG-devel' = headers and so on for dev and deps
'openMVG_samples' = examples
The xxx-devel mecanism will be applied to everything even original Arch scripts. As you can see it differs quite a lot from existing AUR Arch methodology. Some tools needs optimizations for our needs. That's why in the next future you will see xxx-nuxsfm.pkg.tgz That means it uses AUR modified scripts. The naming xxx-nuxsfm.pkg.tgz is applied to avoid conflicting packages with official Arch ones they will replace.
Of course a repo with all packages will be available when all scripts will be written.
2/ It will finally comes with a native installation process of course. In fact it will consist in the usual way of installing Arch, adding a simple line in pacman.conf and run a single pacman -Sy sfm to get everything working about SFM. 
Same thing you saw in my videos, but it was on a LFS on which i implemented the Arch packager.
By now what will provide 2.0 is:
SFM (including scientifics libs): openMVG, openMVS, VisualSFM, SIFT, CMVS/PMVS, Regard3D, MVE,Theia,MicMac,PPT,bundler and some stuff about SLAM.
3D: Blender, CloudCompare, Meshlab
Don't hesitate to ask questions, post any remarks an do on here.

Regards,

PY

**Comment by stephane-lb** [comment]
Hi Pierre Yves,

First of all thank you very much for your quick and detailed answer ! I am really sorry not be as efficient as you. I got some difficulties to virtualise my Arch, now everything is right, so I can start to follow your instruction. It might be possible

**Comment by pyp22** [comment]
see https://github.com/pyp22/NuxSFM-2.0/wiki/Packages-build-and-installation-quick-HowTo
